version: '2'
services:
  camera:
    command: /usr/bin/node /opt/shinobi/camera.js
    build:
      context: .
    restart: always
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET}
    ports:
      - 8080:8080
    volumes:
      - ./videos:/opt/shinobi/videos
      - ./dbdata:/opt/dbdata
  cron:
    env_file: docker.env
    command: /usr/bin/node /opt/shinobi/cron.js
    build:
      context: .
    restart: always
    environment:
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET}
    volumes:
      - ./videos:/opt/shinobi/videos
      - ./dbdata:/opt/dbdata